### ISSUE TITLE
Viper discussion

### ISSUE THREAD

**Issue by denbezrukov** [aspirity-ru/ViperListExample-iOS#2]
Добрый день, увидел вк ваш пост и решил посмотреть, так как сам сейчас перехожу на данный вид архитектуры.
Сразу возникли вопросы:
1)
Рассмотрим пример презентера ListPresenter:
`{
 let interactor: ListInteractorInterface?
    var view: ListViewInterface?
    var wireframe: ListWireframeInterface? }`

и его аутпута т.е. вью

`var presenter: ListPresenterInterface?`

Они держат на друг друга сильные ссылки и поэтому этот модуль не задеалочится. 
Соответственно лучше сделать так: вью на презентор держит сильную ссылку, а тот в свою очередь держит сильные ссылки на роутер и на интерактор, а слабую на вью. Соответственно интерактор держит уже слабую ссылку на презентор. 
2) 
Рассмотрим структуру вью ListViewController:

`var presenter: ListPresenterInterface?
    var items: [ListItem] = Array()`

и
метод DetailsViewController:
`  
func showData(url: String?, title: String?) {

```
    self.navigationItem.title = title
    if url == nil {
        self.loadingIndicator.stopAnimating()
        return
    }
    Alamofire.request(.GET, url!).responseImage { response in
        if let image = response.result.value {
            self.imageView.image = image
            self.cache?.addImage(image, withIdentifier: url!)
            self.loadingIndicator.stopAnimating()
            self.imageView.hidden = false
        }
    }
}
```

`
Как описывает вью рамблер:

> View: отвечает за отображение данных на экране и оповещает Presenter о действиях пользователя. Пассивен, сам никогда не запрашивает данные, только получает их от презента.

в ListViewController он держит массив объектов items.
а DetailsViewController делает запрос для изображения.
Соответсвенно следуя идеи структуры вайпера: вью только запрашивает конкретные действия или объекты у перезентера, а тот в свою очередь знает как обработать эти запросы (у роутера или у интерактора) и отдает их вью. 
Хотя тут тоже скорее лучше сделать разделение, как сказал мой товарищ:

> логика поведения - презентер
> логика данных - интерактор

Поэтому, как говорит рамблер, интерактор это некий фасад сервисов. Хотя мы не до конца согласны с определением сервиса, которое приводит рамблер. И проектируем их следующим образом: это некие абстрактные вещи от которых требуются определенные вещи ( запросы бд(никакой кор даты или реалама) или сети ), но реализация для определенных объектов это некие стратегии, которыми пользуются сервисы.

Так же отдельная тема для обсуждения это роутинг, в своих проектах мы используем асинк, поэтому не пользуемся сторибордами. Facebook приводит забавную фразу:

> "storyboards are incompatible with truth and beauty"

Так же хотел спросить почему используете Swinject ведь Typhoon удобнее(свизлинг же:D ). Конечно, Typhoon использует рантайм objc, что делает невозможным использования генетиков и напрямую inout. Но в данном проекте их нет.

Сорян за кривые вставки кода, git что-то не хочет нормально вставлять их(
Заранее спасибо за ответы. Хочется освоить данную архитектуру, уж очень весомые плюсы.
Если интересно могу показать свой небольшой проект на этой структуре. [вк](https://vk.com/dominion1)

**Comment by iwheelbuy** [comment]
2) Действительно, расположение массива items во View похоже на архитектуру MVC, а не на VIPER. Возможно в таком небольшом проекте будет не так критично расположение массива с данными. Если рассмотреть более крупный проект, где, например, важной задачей будет старый массив данных сравнивать с новым, анимированно удалять/вставлять/перезагружать ячейки коллекции. Так вот в таком проекте вся логика по сравнению старого массива с новым будет происходить во View (из-за расположения в нем старого массива items), что в свою очередь будет соответствовать подходам MVC

**Comment by NamtarR** [comment]
Спасибо за ваши замечания, действительно очень ценные советы! Обо всем поподробнее:
1. Насчет ссылок View и Presenter - таки да, стоит одну сделать слабой, это позже мы исправим. А насчет Presenter-Interactor: за счет реактивности получается, что Interactor не имеет ссылки на Presenter и, поэтому, в этом случае подобной проблемы нет.
1. Здесь на самом деле встает вопрос: а кто будет управлять таблицей? И варианта ответа два: 
   1) ViewController, тогда ему нужен некий набор данных, которые он мог бы отображать.
   2) Presenter, тогда он, по сути, начинает выполнять чужие действия.

Я при создании этого примера и настоящих приложений опирался на статью на [objc.io](https://www.objc.io/issues/13-architecture/viper/), в которой описана схема, при которой Presenter готовит данные для View и отдает ей только то, что нужно показать. А View сама является и DataSource и Delegate для своей таблицы. 
Думаю, в зависимости от задачи что-то может меняться и это нормально.
DetailsViewController вообще на самом деле слишком простой, чтобы была необходимость расписывать его полностью по VIPER, поэтому сделано пока так, как сделано. Опять же, как я писал выше, этот проект, скорее всего, будет переписываться (хотя бы просто на Swift 3, а дальше будет видно).
1. Роутинг. Опять же, в статье на objc.io приводятся такие строки:

> Almost as controversial as Core Data are UI Storyboards. Storyboards have many useful features, 
> and ignoring them entirely would be a mistake. However, it is difficult to accomplish all of the goals
> of VIPER while employing all the features that a storyboard has to offer.
> The compromise we tend to make is to choose not to use segues. 

Поэтому от Storyboard-ов я не отказываюсь, а переходы между контроллерами делаю без Segue.
1. С Typhoon-ом у меня были какие-то проблемы, я пробовал его, но потом для экономии времени решил отказаться в пользу Swinject. Будет время - обязательно сделаю еще одну попытку разобраться с Typhoon-ом:)

Если есть еще какие-то комментарии, замечания, мои косяки - буду рад обсудить:)
